name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli
      - name: Build part 1
        run: "cargo build --release --target wasm32-unknown-unknown"
      - name: Build part 2
        run: 'wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "flee-ai-test" ./target/wasm32-unknown-unknown/release/flee-ai-test.wasm'

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
